-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th2 17, 2022 lúc 07:50 AM
-- Phiên bản máy phục vụ: 10.4.21-MariaDB
-- Phiên bản PHP: 7.4.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `mock`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `posts`
--

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `category_id` int(11) NOT NULL,
  `public_time` datetime NOT NULL DEFAULT current_timestamp(),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Đang đổ dữ liệu cho bảng `posts`
--

INSERT INTO `posts` (`id`, `title`, `content`, `image_url`, `category_id`, `public_time`, `created_at`, `updated_at`) VALUES
(1, 'Nguyễn Hoàng Đức: Từ viên ngọc thô tới Quả bóng vàng Việt Nam', '                                Tối 16/2, tiền vệ Hoàng Đức trở thành chủ nhân của Quả bóng vàng Việt Nam 2021. Đây là phần thưởng xứng đáng sau những gì cầu thủ người Hải Dương thể hiện ở CLB Viettel và đội tuyển Việt Nam trong năm vừa qua.\r\n\r\nHoàng Đức cho biết anh rất bất ngờ khi là người chiến thắng trong \"cuộc đua\" với các đối thủ mạnh như Quang Hải, Tiến Linh. Chân sút quê Hải Dương vẫn vậy, hiền lành, chân thành và khiêm tốn.\r\n\r\nNhưng sự khiêm nhường của Hoàng Đức càng khiến danh hiệu mà anh vừa giành được thêm đẹp và ý nghĩa. Những đóng góp của tiền vệ CLB Viettel âm thầm, nhưng lại mang tới nhiều cảm hứng với đội bóng, mang tới những cảm xúc đặc biệt với người xem trong mỗi trận đấu.                                   ', 'hoangduc2.jpeg', 4, '2022-02-17 10:17:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(2, 'Djokovic được tạo cơ hội để dự Wimbledon ', '                                Cựu tay vợt Tim Henman, thành viên ban tổ chức Wimbledon chia sẻ trên BBC: \"Vào lúc này, Vương quốc Anh không cấm người chưa tiêm vaccine phòng Covid-19 nhập cảnh, do đó Novak Djokovic có thể tới đây.\r\n\r\nCLB Quần vợt Toàn Anh không có quy định riêng cho vấn đề này. Chúng tôi đảm bảo quy định của Chính phủ và nếu Djokovic làm theo hướng dẫn, cậu ấy sẽ chơi ở Wimbledon. Tôi không nghi ngờ điều này\".                            ', 'jokovik.jpeg', 4, '2022-02-17 10:21:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(3, 'Vì sao Lionel Messi sút phạt đền ngày càng tệ hại?', 'Thực tế, không phải tới tận bây giờ mà trong nhiều năm qua, Messi vẫn bị ám ảnh như vậy khi bước lên chấm 11 mét. Điển hình nhất là tình huống ngôi sao này sút phạt đền hỏng ăn khiến đội tuyển Argentina mất chức vô địch Copa America 2016 trước Chile.\r\n\r\nTheo thống kê, trong sự nghiệp, Messi đã thực hiện 103 cú sút phạt đền nhưng hỏng ăn tới… 30 lần. Đó là tỷ lệ tương đối cao. Tính riêng ở Champions League, siêu sao người Argentina cũng thực hiện không thành công 5 lần sau 23 lần thực hiện (kỷ lục ở giải đấu).\r\n\r\nVậy tại sao Messi bị ám ảnh sút phạt đền tới vậy dù cho mọi kỹ thuật của cầu thủ này ở mức thượng thừa?\r\n\r\nNhà báo Ben Lyttleton, tác giả của cuốn sách \"Twelve Yards: The Art & Pscyhology of the Perfect Penalty\" (tạm dịch là 12 yard: Nghệ thuật và tâm lý của cú sút phạt đền hoàn hảo) từng phân tích về vấn đề này.', 'messi.jpg', 4, '2022-02-17 10:22:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(4, 'Thái Lan bất ngờ thay đổi tên thủ đô', 'Văn phòng Hội Hoàng gia Thái Lan (ORST) ngày 16/2 thông báo, tên chính thức của thủ đô sẽ chuyển từ Bangkok sang Krung Thep Maha Nakhon theo tiếng Thái Lan, song tên cũ vẫn được công nhận. Sự thay đổi này đã được nội các Thái Lan phê chuẩn nhưng vẫn cần sự phê duyệt của một ủy ban đặc biệt của chính phủ trước khi có hiệu lực.\r\n\r\nThông báo về việc thay đổi tên thủ đô đã kéo theo các cuộc tranh luận sôi nổi trên mạng xã hội. ORST lý giải, việc thay đổi này là cần thiết để phản ánh đúng hơn \"tình hình hiện tại\".\r\n\r\nTên gọi thủ đô Bangkok là thủ đô của Thái Lan phổ biến từ rất lâu, nhưng chính thức được Văn phòng Hội Hoàng gia tuyên bố sử dụng từ tháng 11/2001. Tên gọi Bangkok bắt nguồn từ một khu vực cũ của Bangkok và hiện là một phần trong đại đô thị lớn hơn, bao gồm các quận Bangkok Noi và Bangkok Yai.\r\n\r\nTrong tiếng Thái, Krung Thep Maha Nakhon có nghĩa là \"Thành phố thủ đô của các thiên thần vĩ đại\". Tên gọi mới này nghe có vẻ dài so với tên gọi cũ nhưng thực chất đã là cách viết tắt theo tiếng Thái Lan.', 'thailand2.jpg', 1, '2022-02-17 10:23:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(5, '24 tàu chiến Nga tập trận ngoài khơi Nhật Bản 123', '                                Bộ Quốc phòng Nhật Bản ngày 15/2 xác nhận, một hạm đội gồm 24 tàu chiến Nga đã diễn tập ở vùng biển Nhật Bản và vùng biển Okhotsk, ngoài khơi Hokkaido kể từ ngày 1/2. Các tàu này bao gồm cả tàu ngầm, tàu khu trục và tàu hộ vệ.\r\n\r\nBộ trưởng Quốc phòng Nhật Bản Nobuo Kishi cho biết, động thái này của Nga diễn ra trùng thời điểm Nga tăng cường hiện diện quân sự gần Ukraine. Theo ông, với động thái này, Moscow có lẽ muốn thể hiện có khả năng tiến hành các hoạt động quân sự cùng một lúc ở cả phía đông và phía tây lãnh thổ.\r\n\r\n\"Đợt triển khai này khá bất thường về cả quy mô và thời gian\", James Brown, phó giáo sư về quan hệ quốc tế thuộc Đại học Temple ở Tokyo, nhận định. Ông lưu ý thêm, vùng biển Okhotsk rất khắc nghiệt, do vậy hoạt động quân sự được cho là khá mạo hiểm.\r\n\r\nVề thời gian, ông Brown tin rằng, động thái triển khai này của Nga có mối liên hệ với tình hình căng thẳng ở biên giới Nga - Ukraine những tuần gần đây. Theo ông, đó là cách để Nga gửi thông điệp nắn gân tới Mỹ và các đồng minh.\r\n\r\n\"Rõ ràng Nga muốn nói với Nhật Bản rằng, họ không nên ngả về Mỹ và châu Âu trong các chính sách về Ukraine, họ nên gạt bỏ sức ép phải áp lệnh trừng phạt Nga\", Toshimitsu Shigemura, giáo sư về quan hệ quốc tế tại Đại học Waseda, nhận định.                                          ', 'tauchien.jpg', 1, '2022-02-17 10:24:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(6, 'Nước cờ liên tiếp của Nga khiến phương Tây \"xoay như chong chóng\"', 'Giữa lúc căng thẳng leo thang gần như đến mức đỉnh điểm và phương Tây dự đoán xung đột có thể sẽ nổ ra ngay trong tuần này, Tổng thống Putin đã xác nhận tại buổi họp báo sau cuộc gặp với Thủ tướng Đức Olaf Scholz hôm 15/2 rằng, một phần của quân đội Nga sẽ được rút khỏi khu vực biên giới Ukraine.\r\n\r\nBộ Quốc phòng Nga cũng thông báo, một số đơn vị của quân đội Nga sẽ rút về căn cứ sau cuộc tập trận ở biên giới Ukraine. Phía Nga nói rằng binh sĩ của nước này đã hoàn tất một số cuộc tập trận quân sự ở Belarus, gần biên giới Ukraine và sẽ bắt đầu rút về vị trí triển khai thường trực.\r\n\r\nTuy nhiên, Nga chưa rút toàn bộ lực lượng về nước và một số cuộc tập trận vẫn tiếp tục diễn ra. Trước đó, Nga thông báo cuộc tập trận quân sự chung với Belarus sẽ kéo dài 10 ngày, bắt đầu từ 10/2. Cuộc tập trận không chỉ diễn ra ở khu vực gần biên giới Ukraine, mà còn gần biên giới Ba Lan và Lithuania, 2 nước thành viên của NATO.   ', 'nga2.jpeg', 1, '2022-02-17 10:25:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(7, 'Cung không đủ cầu, giá dầu có thể lên tới 150 USD/thùng', 'Kể từ tháng 12 năm ngoái đến nay, giá dầu Brent đã tăng khoảng 20 USD/thùng trong bối cảnh lo ngại nguồn cung, lạm phát cao và căng thẳng địa chính trị. Tuần trước giá dầu Brent đã vượt mốc 95 USD/thùng, mức cao nhất kể từ mùa hè năm 2014, và tăng 63% so với cùng kỳ năm ngoái. Hiện giá dầu Brent đang giao dịch ở mức 94,81 USD/thùng.\r\n\r\nCác nhà phân tích năng lượng dự đoán, giá dầu Brent vượt ngưỡng 100 USD/thùng gần như có thể đạt được trong thời điểm này. Nhưng giờ đây, ngày càng có nhiều dự báo cho rằng giá dầu có thể vượt 125 USD/thùng, thậm chí cao hơn.\r\n\r\nÔng John Driscoll, giám đốc JTD Energy Services nói với CNBC rằng nguồn cung dầu vật chất đang thiếu vì vậy giá dầu có khả năng vượt 120 USD/thùng, thậm chí lên tới 150 USD/thùng.\r\n\r\nCăng thẳng ở biên giới Nga và Ukraine đã khiến giá dầu tăng vọt. Mặc dù Nga đã tuyên bố rút một phần binh lính khỏi biên giới Ukraine và bác bỏ tấn công quân sự song NATO và Tổng thống Mỹ Biden vẫn khẳng định nguy cơ chiến tranh vẫn còn cao.\r\n\r\nNgoài ra, theo ông Driscoll, thị trường đang ở trong tình trạng giá giao ngay cao hơn cả giá hợp đồng tương lai. \"Chúng tôi cũng nhận thấy nhu cầu đang trên đà phục hồi trong khi nguồn cung thiếu hụt\", ông nói.', 'dau.jpeg', 2, '2022-02-17 10:27:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(8, 'FWD khép lại năm 2021 thành công, mở ra năm 2022 đầy triển vọng', 'Xuất hiện bên cạnh các cầu thủ nữ của mình, nhân ngày họ được vinh danh ở giải thưởng QBV Việt Nam năm 2021, HLV Mai Đức Chung rất hạnh phúc về thành công của các học trò trong năm qua và đầu năm 2022.\r\n\r\nThành tích giành suất dự VCK World Cup 2023 của đội tuyển bóng đá nữ Việt Nam không được tính cho kết quả bầu chọn QBV năm 2021, do giải vô địch châu Á mà các cầu thủ nữ vừa tham dự tại Ấn Độ, đã bước sang năm 2022. Tuy nhiên, thành tích đấy vẫn ghi dấu ấn trong lòng khán giả.', 'fwd.jpeg', 2, '2022-02-17 10:28:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(9, 'ThaiBev đều đặn nhận cổ tức hàng trăm tỷ đồng từ Sabeco', 'Hội đồng quản trị (HĐQT) Tổng Công ty Cổ phần Bia - Rượu - Nước giải khát Sài Gòn (Sabeco, mã chứng khoán: SAB) vừa thông qua nghị quyết tạm ứng cổ tức bằng tiền mặt năm 2021 với tỷ lệ chi trả 15% trên mệnh giá cổ phiếu. Cổ đông sở hữu mỗi cổ phần sẽ nhận về tương ứng 1.500 đồng.\r\n\r\nThời gian chốt danh sách cổ đông là ngày 3/3. Thời gian chi trả cổ tức dự kiến là 23/3. Đặc biệt, Sabeco cũng vừa mới hoàn tất đợt trả cổ tức gần nhất vào cuối tháng 1, ngay trước kỳ nghỉ Tết. \r\n\r\nVới hơn 641 triệu cổ phiếu đang lưu hành, ước tính Sabeco sẽ cần chi hơn 960 tỷ đồng để trả cổ tức cho cổ đông trong tháng 3 tới. Trong đó, hai cổ đông lớn nhất là Vietnam Beverage và Tổng công ty Đầu tư Kinh doanh vốn Nhà nước (SCIC) lần lượt nhận 515 tỷ đồng và 346 tỷ đồng. \r\n\r\nVietnam Beverage là doanh nghiệp thuộc tập đoàn ThaiBev của tỷ phú Thái Lan Charoen Sirivadhanabhakdi. Đây là pháp nhân đại diện ThaiBev tham gia mua 53,6% cổ phần Sabeco trong đợt thoái vốn của Bộ Công Thương cuối năm 2017. Sau khi bán vốn cho đối tác Thái Lan, Bộ Công Thương sở hữu 36% cổ phần Sabeco rồi sau đó chuyển giao phần vốn này cho SCIC quản lý.\r\n\r\nTrong đợt nhận cổ tức vào cuối tháng 1, phía ThaiBev cùng SCIC cũng đã nhận về lần lượt 687 tỷ đồng và 462 tỷ đồng. Trên sàn chứng khoán, Sabeco nằm trong số ít doanh nghiệp quy mô lớn chi trả cổ tức cao, đều đặn qua nhiều năm.', 'sabeco.png', 2, '2022-02-17 10:28:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(10, 'Amee được quảng bá tại Quảng trường Thời Đại', '<p><span style=\"color: rgb(77, 77, 77); font-family: Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", sans-serif; font-size: 17px;\">Mở bát năm 2022, Amee có nhiều hoạt động quảng bá hình ảnh tích cực tại thị trường trong nước lẫn quốc tế. Vừa qua, cô vinh dự là đại diện tiếp theo của Vpop được quảng bá tại Quảng trường Thời Đại, Mỹ, nhân dịp trở thành nghệ sĩ hoạt động trong chiến dịch Equal của Spotify. Hình ảnh nữ ca sĩ được phủ sóng trên billboard giữ vị trí đắc địa ở thành phố New York là sự đền đáp cho nỗ lực chứng minh tiềm năng và vị thế của Amee.</span></p><p><span style=\"color: rgb(77, 77, 77); font-family: Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", sans-serif; font-size: 17px;\">Trước đó, Amee cũng gặt hái nhiều thành tích ấn tượng tại đường đua âm nhạc khi comeback cùng MV Thay mọi cô gái yêu anh, thuộc dự án hợp tác cùng Lotteria - nhãn hàng cô đang đảm nhận vai trò đại sứ thương hiệu. Là đại sứ trẻ tuổi, Amee vẫn chứng tỏ được sức ảnh hưởng \"không phải dạng vừa\" khi thành công truyền tải hình ảnh thân thiện, gần gũi mà Lotteria muốn hướng đến. Nhờ giai điệu ngọt ngào, hình ảnh đậm chất thơ, MV nhanh chóng \"đua top\" tại nhiều bảng xếp hạng uy tín, giữ vị trí top 4 trending Youtube, #3 Zingchart, #3 Apple Music, #2 tại Hot Hits Việt Nam, #5 tại Top 50 Spotify Việt Nam. Thử thách duet Thay mọi cô gái yêu anh cùng Amee trên Tiktok cũng gây sốt với loạt clip viral mạng xã hội.</span><span style=\"color: rgb(77, 77, 77); font-family: Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Helvetica Neue\", Arial, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", sans-serif; font-size: 17px;\"><br></span>                            </p>', 'amee.jpeg', 3, '2022-02-17 10:30:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(11, 'Song Hye Kyo nổi loạn, kiêu sa giữa thời điểm ', '                                Ngày 10/2 mới đây, cặp đôi Hạ cánh nơi anh đã gây xôn xao mạng xã hội châu Á khi thông báo tiến tới hôn nhân sau gần 2 năm hò hẹn. Cặp đôi nhận được lời chúc phúc của đồng nghiệp và cộng đồng mạng. Hôn lễ diễn ra vào tháng 3 tới đây của họ chính là một trong những sự kiện được chờ đợi nhất năm 2022 của làng giải trí xứ Hàn. \r\n\r\nSong Hye Kyo, một trong những cô gái từng công khai hò hẹn với Hyun Bin, cũng nhận được sự quan tâm của dư luận. Cô và Hyun Bin từng ở bên nhau gần 2 năm trước khi xác nhận chia tay. Cặp đôi bén duyên từ lần hợp tác trong bộ phim truyền hình The World Within.                            ', 'vo2.jpg', 3, '2022-02-17 10:32:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(12, 'Vợ của Tom Cruise bị ngã khi dự tuần lễ thời trang New York', '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Tuần lễ thời trang New York (Mỹ) được tổ chức vào tháng 2 và tháng 9 hàng năm. Đây là một chuỗi sự kiện nửa năm diễn ra một lần (thường kéo dài từ 7 - 9 ngày).\r\n\r\nTại tuần lễ thời trang uy tín này, các nhà thiết kế giới thiệu các bộ sưu tập thời trang mới nhất tới với các khách hàng, báo chí và công chúng. Tuần lễ thời trang New York là một trong bốn tuần lễ thời trang lớn trên thế giới, cùng với các tuần lễ thời trang ở Paris, London và Milan.\r\n\r\nTuần lễ thời trang New York đầu tiên được tổ chức vào năm 1943 bởi Eleanor Lambert, giám đốc truyền thông của viện trang phục New York. Hội đồng các nhà thiết kế thời trang Mỹ (CFDA) đã tạo ra khái niệm hiện đại về \"Tuần lễ thời trang New York\" vào năm 1993. Địa điểm chính diễn ra tuần lễ thời trang New York là ở Spring Studios tại số 50 phố Varick, New York, Mỹ.\r\n\r\nTuần lễ thời trang New York năm nay bắt đầu diễn ra sôi động từ ngày 12/2. Hàng loạt các ngôi sao đình đám thế giới đang tụ họp về New York, Mỹ để xem các buổi trình diễn thời trang lớn và cập nhật các xu hướng thời trang mới nhất. \r\n\r\nTối 12/2, nữ diễn viên Katie Holmes, vợ cũ của tài tử Tom Cruise đã tới xem buổi ra mắt bộ sưu tập mới của thương hiệu Alice + Olivia. Đây là thương hiệu được các ngôi sao của Mỹ rất yêu thích.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ', 'new4.jpg', 3, '2022-02-17 10:32:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(13, 'hlv Mai Đức Chung: \\\\', '                                                                                                                                Xuất hiện bên cạnh các cầu thủ nữ của mình, nhân ngày họ được vinh danh ở giải thưởng QBV Việt Nam năm 2021, HLV Mai Đức Chung rất hạnh phúc về thành công của các học trò trong năm qua và đầu năm 2022.\r\n\r\nThành tích giành suất dự VCK World Cup 2023 của đội tuyển bóng đá nữ Việt Nam không được tính cho kết quả bầu chọn QBV năm 2021, do giải vô địch châu Á mà các cầu thủ nữ vừa tham dự tại Ấn Độ, đã bước sang năm 2022. Tuy nhiên, thành tích đấy vẫn ghi dấu ấn trong lòng khán giả.\r\nNgười hâm mộ chú ý đặc biệt đến các thành viên của đội tuyển bóng đá nữ Việt Nam, trong đêm Gala trao giải QBV Việt Nam tại TPHCM tối qua, cũng xuất phát từ tấm vé dự World Cup.\r\n\r\nVà trong buổi tối đặc biệt ấy, HLV Mai Đức Chung đã chia sẻ: \"Thời điểm mà FIFA quyết định tăng số đội dự VCK World Cup từ 24 đội lên 32 đội là vào năm 2017. Năm đó, tôi vẫn còn nắm một đội bóng đá nam là CLB Thanh Hóa tại V-League\".\r\n\r\n\"Khi biết thông tin này, tôi cho rằng cơ hội để dự World Cup của bóng đá nữ Việt Nam đã đến. Nên khi anh Trần Quốc Tuấn (hiện là Quyền chủ tịch VFF), khi đó còn là Phó chủ tịch VFF đặt vấn đề với tôi, tôi đồng ý ngay và quay lại nắm đội tuyển bóng đá nữ\" - vị HLV trưởng của đội tuyển bóng đá nữ Việt Nam nói thêm.                                                                                                                ', 'mdc.jpeg', 4, '2022-02-17 10:35:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
